[build]
  base = "frontend"
  publish = "build"
  command = "npm run build"

[[headers]]
  for = "/serviceWorker.js"
  [headers.values]
    Cache-Control = "no-cache"
    Content-Type = "application/javascript"
    Service-Worker-Allowed = "/"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    Content-Type = "image/png"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9" 